owner: robert-wettstaedt
repo: grnyte-status
user-agent: robert-wettstaedt

sites:
  - name: Prod
    url: https://grnyte.rocks
  - name: Prod sync
    url: https://zero.grnyte.rocks
  - name: Prod accounts
    url: https://vamttgjugazgeujczjcr.supabase.co/auth/v1/health
  - name: Demo
    url: https://demo.grnyte.rocks
  - name: Demo sync
    url: https://zero.demo.grnyte.rocks
  - name: Demo accounts
    url: https://niniugtqbfituyzfoapv.supabase.co/auth/v1/health

status-website:
  cname: status.grnyte.rocks
  name: grnyte status
  logoUrl: https://grnyte.rocks/pwa-192x192.png
  theme: dark
  navbar:
    - title: Status
      href: /
    - title: grnyte
      href: https://grnyte.rocks
